name: Update Frontend

on:
  # run manually
  workflow_dispatch:
  # timezone UTC
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repo
        uses: actions/checkout@v3
      - name: checkout storycoder.dev repo
        uses: actions/checkout@v3
        with:
          repository: roseTech/storycoder.dev
          path: ./storycoder.dev
      - name: setup node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm clean-install
      - name: run examples
        run: npm run examples
      - name: check for new commits
        working-directory: storycoder.dev
        run: |
          echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV
      - name: run update
        run: npm run update
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        env:
          WP_URL: ${{ vars.WP_URL }}
          WP_API_USERNAME: ${{ vars.WP_API_USERNAME }}
          WP_API_PASSWORD: ${{ secrets.WP_API_PASSWORD}}
          STORIES_ROOT: ${{ vars.STORIES_ROOT }}
