name: Update Frontend

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current repo
        uses: actions/checkout@v3
      - name: checkout storycoder.dev repo
        uses: actions/checkout@v3
        with:
          repository: roseTech/storycoder.dev 
          path: './storycoder.dev'
      - name: setup node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: npm clean-install
      - name: list directories
        run: ls -al
      - name: run examples
        run: npm run examples
      - name: API # remove if everything is working as expected
        run: echo URL:$WP_URL STORIES_ROOT:$STORIES_ROOT
        env:
          WP_URL: https://storycoder.dev
          STORIES_ROOT: ${{ vars.STORIES_ROOT }}
      - name: run update
        run: npm run update
        env:
          WP_URL: https://storycoder.dev
          WP_API_USERNAME: https://practicecoding.dev
          # just for a test will be removed in an hour (2023-04-20 10:57)
          WP_API_PASSWORD: 5OQF 4JL6 qY8U iZzv 4Jxn YVWQ
          STORIES_ROOT: storycoder.dev
