name: Update Frontend

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current repo
        uses: actions/checkout@v3
      - name: checkout storycoder.dev repo
        uses: actions/checkout@v3
        with:
          repository: roseTech/storycoder.dev 
          path: './storycoder.dev'
      - name: list directories
        run: ls -al
      - name: setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: npm clean-install
      - name: run examples
        run: npm run examples
      - name: API # remove if everything is working as expected
        run: echo $WP_URL $STORIES_ROOT
        env:
          WP_URL: ${{ vars.WP_URL }}
          STORIES_ROOT: ${{ vars.STORIES_ROOT }}
      - name: run update
        run: npm run update
        env:
          WP_URL: ${{ vars.WP_URL }}
          WP_API_USERNAME: ${{ secrets.WP_API_USERNAME }}
          WP_API_PASSWORD: ${{ secrets.WP_API_PASSWORD}}
          STORIES_ROOT: ${{ vars.STORIES_ROOT }}
